spring:
  application:
    name: file
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans_backend
    username: root
    password: wangze512
  rabbitmq:
    connection-timeout: 1s
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: false # 禁用自动重试(springboot默认开启 提供的消费者内部的重试)
    template:
      retry:
        enabled: true # 开启超时重试机制  发送方重试
      mandatory: true # 开启强制投递机制
    publisher-returns: true  # 开启发布确认机制
    publisher-confirm-type: correlated
    host: localhost
    port: 5672
    username: guest
    password: guest
  elasticsearch:
    uris: http://localhost:9200
  redis:
    port: 6379
    host: 127.0.0.1
  profiles:
    active: local


server:
  port: 8082
  servlet:
    context-path: /file

minio:
  endpoint: http://localhost:9000
  bucketName: test
  accessKey: minioadmin
  secretKey: minioadmin

baidu:
  appId: your_app_id
  secretKey: your_secret_key
aliyun:
  apiKey: your_api_key
elasticsearch:
  host: localhost
  port: 9200
  scheme: http

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.example.trans_backend_file.controller
