spring:
  application:
    name: file
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans_backend
    username: root
    password: wangze512
  rabbitmq:
    connection-timeout: 1s
    template:
      retry:
        enabled: true # 开启超时重试机制
    publisher-returns: true
    publisher-confirm-type: correlated
    host: localhost
    port: 5672
    username: guest
    password: guest
  elasticsearch:
    uris: http://localhost:9200


server:
  port: 8082
  servlet:
    context-path: /file

minio:
  endpoint: http://localhost:9000
  bucketName: test
  accessKey: minioadmin
  secretKey: minioadmin

baidu:
  appId: your_app_id
  secretKey: your_secret_key
aliyun:
  apiKey: your_api_key
elasticsearch:
  host: localhost
  port: 9200
  scheme: http
