server:
  port: 8080
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans_backend
    username: root
    password: wangze512
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" # 跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: admin
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**
        - id: file
          uri: http://localhost:8082
          predicates:
            - Path=/file/**
        - id: websocket
          uri: ws://localhost:8083
          predicates:
            - Path=/socket/ws/**
          filters:
            - StripPrefix=1 # 去掉前缀
  main:
    web-application-type: reactive
  web:
    resources:
      static-locations: classpath:/web/

auth:
 loginUrl: http://localhost:8080/test.html
gateway:
  ipRateEnable: false
  ipRateList:
#    测试数据
    - ip: 1
      rate: 1
      capacity: 1
  ignore:
    urls:
      - "/admin/login"
      - "/admin/register"